name: Trivy IaC Scan

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-iac:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy (latest)
        uses: aquasecurity/setup-trivy-action@v0.2.5

      - name: Run Trivy IaC Scan (Terraform)
        run: |
          trivy iac config \
            --format sarif \
            --output trivy-results.sarif \
            .

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

