name: trivy-iac

on:
  push:
    branches: [ dev ]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-iac:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.65.0

      - name: Run Trivy IaC scan
        run: |
          trivy iac --format sarif --output trivy-iac.sarif .

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-iac.sarif
